---
author: "Юрій Клебан"
date: "`r Sys.Date()`"
date-format: short
---

# Що таке Quarto?

**`Quarto`** - це науково-технічна видавнича система з відкритим кодом.

За допомогою `Quarto` можна виконувати наступні дії:

-   Писати код за допомогою `Jupyter Notebook`-ів або розмітки звичайного тексту (`markdown`) у вашому улюбленому редакторі.
- Створювати динамічний вміст за допомогою `Python`, `R`, `Julia` та `Observable`.
- Публікувати якісні статті, презентації, веб-сайти, блоги та книги у форматах `HTML`, `PDF`, `MS Word`, `ePub` тощо.
- Пишіть за допомогою розмітки `Pandoc`, включаючи формули, цитати, перехресні посилання, фігури, блок-схеми, виноски тощо.

Розробники `Quarto` користуються наступними слоганами:

> Аналізуйте. Поділіться. Відтворіть.
>
> У вас є історія, яку можна розповісти за допомогою даних --- розкажіть це за допомогою Quarto.

**`Quarto`** --- це багатомовна версія наступного покоління `R Markdown` від `Posit` із багатьма новими функціями та можливостями. Подібно до `R Markdown`, `Quarto` використовує `knitr` для виконання `R`-коду, і тому може відтворювати більшість існуючих файлів `Rmd` без змін.

::: {.callout-note}
Зверніть увагу, що Ви можете конвертувати у порібний формат як `Jupyter Notebook`, так і `Markdown` файли.
:::
