---
author: "Юрій Клебан"
date: "`r Sys.Date()`"
description: "Some text"
date-format: short
---

# Правила оформлення розмітки

## Робота з виносками

*Виноски* є хорошим спосбом звернути увагу читачів на деякий контент. Зокрема, Ви можете скористатися 5-ма стилями для виносок за замовчуванням: `note`, `warning`, `important`, `tip`, `caution` [@quarto].

Колір та іконка будуть різнитися, залежно від типу виноски, яку ви обрали. Розглянемо приклади коду та зовнішній вигляд таких компонентів.

Так, наприклад, нотатки (`note`) будуть візуалізовані наступним кодом:

```r
::: {.callout-note}
Зверніть увагу, що Ви можете використовувати:
`note`, `warning`, `important`, `tip`, and `caution`.
:::
```

Результат:

::: {.callout-note}
Зверніть увагу, що Ви можете використовувати:
`note`, `warning`, `important`, `tip`, and `caution`.
:::

Розглянемо для прикладу поради (`tip`):

```r
::: {.callout-tip}
## Заголовок поради

Виноски варто використовувати під ча соформлення сайтів, електронних книг.
:::
```

Код із заголовком як параметер:

```r
::: {.callout-tip title="Tip with Title"}
## Заголовок поради

Виноски варто використовувати під ча соформлення сайтів, електронних книг.
:::
```

Результат у обох випадках виглядатиме однаково:

::: {.callout-tip}
## Заголовок поради

Виноски варто використовувати під ча соформлення сайтів, електронних книг.
:::

Іншою корисною функцією може бути згортання/розгортання виносок для економії місця на дисплеї. Це робиться за допомогою параметра `collapse="true"`:

```r
::: {.callout-caution collapse="true"}
## Приклад коду, що згортається

А тут текст :)
:::
```

::: {.callout-caution collapse="true"}
## Приклад коду, що згортається

А тут текст :)
:::

Дтеальніше з інформацією про оформлення виносок можна ознайомитися на сайті @quarto у розділі "Виноски" <https://quarto.org/docs/authoring/callouts.html>.
